### ISSUE TITLE
May we use the freeze.png for DDNet?

### ISSUE THREAD

**Issue by def-** [Speedy-Consoles/teeworlds#9]
Hi Speedy-Consoles,

I didn't find another way to contact you, so here we go:

In a discussion in https://github.com/ddnet/ddnet/pull/2307 it came up that you had a nicer way of showing frozen tee. May we use the freeze.png graphic (https://github.com/Speedy-Consoles/teeworlds/blob/ddrace07/datasrc/freeze.png) you have for that?

Cheers
deen

**Comment by edg-l** [comment]
In my opinion, it looks really bad, we should really maintain the round design of the tee.

**Comment by Speedy-Consoles** [comment]
I didn't put too much effort into it, so i don't mind someone using it. Putting it into ddnet, however, seems to be controversial for other reasons :wink:.
